# Modify name if deploying multiple instances
name = "sub-box"

main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# [placement]
# mode = "smart"

# Environment variables
# Modify these to use the correct environment variables
[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "qq33767078" # Change this to a secure password
JWT_SECRET = "j3n8Su4yYa1L4T3j3IYVEZpeTD6GBqyj5fO5IiMoIx0=" # Change this to a secure secret key
SESSION_TAG = "0"
SESSION_DURATION = "7d"
DEPLOY_TARGET = "cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "prod-sub-box-db" # Change this to the name of your D1 database
database_id = "6f19b28bdb7a42a6b838721694df6859" # wrangler d1 info <YOUR_DATABASE_NAME>

[observability.logs]
enabled = true
